document.webL10n=function(A,k,G){function B(){var c=k.querySelector('script[type="application/l10n"]');return c?JSON.parse(c.innerHTML):null}function t(c){var e=k.createEvent("Event");e.initEvent("localized",!0,!1);e.language=c;k.dispatchEvent(e)}function r(c,e,b){e=e||function(a){};b=b||function(){console.warn(c+" not found.")};var d=new XMLHttpRequest;d.open("GET",c,!0);d.overrideMimeType&&d.overrideMimeType("text/plain; charset=utf-8");d.onreadystatechange=function(){4==d.readyState&&(200==d.status||
0===d.status?e(d.responseText):b())};d.onerror=b;d.ontimeout=b;try{d.send(null)}catch(f){b()}}function C(c,e,b,d){function f(b,c){function d(b,c,h){function s(){for(;;){if(!w.length){h();break}var b=w.shift();if(!m.test(b)){if(c){if(u=q.exec(b)){v=u[1].toLowerCase();r="*"!==v&&v!==e&&v!==t;continue}else if(r)continue;if(u=n.exec(b)){f(a+u[1],s);break}}var d=b.match(l);d&&3==d.length&&(b=d[1],d=d[2],d=0>d.lastIndexOf("\\")?d:d.replace(/\\\\/g,"\\").replace(/\\n/g,"\n").replace(/\\r/g,"\r").replace(/\\t/g,
"\t").replace(/\\b/g,"\b").replace(/\\f/g,"\f").replace(/\\{/g,"{").replace(/\\}/g,"}").replace(/\\"/g,'"').replace(/\\'/g,"'"),g[b]=d)}}}var w=b.replace(k,"").split(/[\r\n]+/),v="*",t=e.split("-",1)[0],r=!1,u="";s()}function f(a,b){r(a,function(a){d(a,!1,b)},null)}var g={},k=/^\s*|\s*$/,m=/^\s*#|^\s*$/,q=/^\s*\[(.*)\]\s*$/,n=/^\s*@import\s+url\((.*)\)\s*$/i,l=/^([^=\s]*)\s*=\s*(.+)$/;d(b,!0,function(){c(g)})}var a=c.replace(/[^\/]*$/,"")||"./";r(c,function(a){l+=a;f(a,function(a){for(var c in a){var d,
e;e=c.lastIndexOf(".");0<e?(d=c.substring(0,e),e=c.substr(e+1)):(d=c,e="textContent");g[d]||(g[d]={});g[d][e]=a[c]}b&&b()})},d)}function D(c,e){function b(a){var b=a.href;this.load=function(a,c){C(b,a,c,function(){console.warn(b+" not found.");console.warn('"'+a+'" resource not found');m="";c()})}}c&&(c=c.toLowerCase());e=e||function(){};g={};m=l="";m=c;var d=k.querySelectorAll('link[type="application/l10n"]'),f=d.length;if(0===f){if((d=B())&&d.locales&&d.default_locale){console.log("using the embedded JSON directory, early way out");
g=d.locales[c];if(!g){var a=d.default_locale.toLowerCase(),h;for(h in d.locales)if(h=h.toLowerCase(),h===c){g=d.locales[c];break}else h===a&&(g=d.locales[a])}e()}else console.log("no resource to load, early way out");t(c);n="complete"}else{h=null;var s=0;h=function(){s++;s>=f&&(e(),t(c),n="complete")};for(a=0;a<f;a++)(new b(d[a])).load(c,h)}}function E(c){function e(a,b){return-1!==b.indexOf(a)}function b(a,b,c){return b<=a&&a<=c}var d={0:function(a){return"other"},1:function(a){return b(a%100,3,
10)?"few":0===a?"zero":b(a%100,11,99)?"many":2==a?"two":1==a?"one":"other"},2:function(a){return 0!==a&&0===a%10?"many":2==a?"two":1==a?"one":"other"},3:function(a){return 1==a?"one":"other"},4:function(a){return b(a,0,1)?"one":"other"},5:function(a){return b(a,0,2)&&2!=a?"one":"other"},6:function(a){return 0===a?"zero":1==a%10&&11!=a%100?"one":"other"},7:function(a){return 2==a?"two":1==a?"one":"other"},8:function(a){return b(a,3,6)?"few":b(a,7,10)?"many":2==a?"two":1==a?"one":"other"},9:function(a){return 0===
a||1!=a&&b(a%100,1,19)?"few":1==a?"one":"other"},10:function(a){return b(a%10,2,9)&&!b(a%100,11,19)?"few":1!=a%10||b(a%100,11,19)?"other":"one"},11:function(a){return b(a%10,2,4)&&!b(a%100,12,14)?"few":0===a%10||b(a%10,5,9)||b(a%100,11,14)?"many":1==a%10&&11!=a%100?"one":"other"},12:function(a){return b(a,2,4)?"few":1==a?"one":"other"},13:function(a){return b(a%10,2,4)&&!b(a%100,12,14)?"few":1!=a&&b(a%10,0,1)||b(a%10,5,9)||b(a%100,12,14)?"many":1==a?"one":"other"},14:function(a){return b(a%100,3,
4)?"few":2==a%100?"two":1==a%100?"one":"other"},15:function(a){return 0===a||b(a%100,2,10)?"few":b(a%100,11,19)?"many":1==a?"one":"other"},16:function(a){return 1==a%10&&11!=a?"one":"other"},17:function(a){return 3==a?"few":0===a?"zero":6==a?"many":2==a?"two":1==a?"one":"other"},18:function(a){return 0===a?"zero":b(a,0,2)&&0!==a&&2!=a?"one":"other"},19:function(a){return b(a,2,10)?"few":b(a,0,1)?"one":"other"},20:function(a){return!b(a%10,3,4)&&9!=a%10||b(a%100,10,19)||b(a%100,70,79)||b(a%100,90,
99)?0===a%1E6&&0!==a?"many":2!=a%10||e(a%100,[12,72,92])?1!=a%10||e(a%100,[11,71,91])?"other":"one":"two":"few"},21:function(a){return 0===a?"zero":1==a?"one":"other"},22:function(a){return b(a,0,1)||b(a,11,99)?"one":"other"},23:function(a){return b(a%10,1,2)||0===a%20?"one":"other"},24:function(a){return b(a,3,10)||b(a,13,19)?"few":e(a,[2,12])?"two":e(a,[1,11])?"one":"other"}},f={af:3,ak:4,am:4,ar:1,asa:3,az:0,be:11,bem:3,bez:3,bg:3,bh:4,bm:0,bn:3,bo:0,br:20,brx:3,bs:11,ca:3,cgg:3,chr:3,cs:12,cy:17,
da:3,de:3,dv:3,dz:0,ee:3,el:3,en:3,eo:3,es:3,et:3,eu:3,fa:0,ff:5,fi:3,fil:4,fo:3,fr:5,fur:3,fy:3,ga:8,gd:24,gl:3,gsw:3,gu:3,guw:4,gv:23,ha:3,haw:3,he:2,hi:4,hr:11,hu:0,id:0,ig:0,ii:0,is:3,it:3,iu:7,ja:0,jmc:3,jv:0,ka:0,kab:5,kaj:3,kcg:3,kde:0,kea:0,kk:3,kl:3,km:0,kn:0,ko:0,ksb:3,ksh:21,ku:3,kw:7,lag:18,lb:3,lg:3,ln:4,lo:0,lt:10,lv:6,mas:3,mg:4,mk:16,ml:3,mn:3,mo:9,mr:3,ms:0,mt:15,my:0,nah:3,naq:7,nb:3,nd:3,ne:3,nl:3,nn:3,no:3,nr:3,nso:4,ny:3,nyn:3,om:3,or:3,pa:3,pap:3,pl:13,ps:3,pt:3,rm:3,ro:9,rof:3,
ru:11,rwk:3,sah:0,saq:3,se:7,seh:3,ses:0,sg:0,sh:11,shi:19,sk:12,sl:14,sma:7,smi:7,smj:7,smn:7,sms:7,sn:3,so:3,sq:3,sr:11,ss:3,ssy:3,st:3,sv:3,sw:3,syr:3,ta:3,te:3,teo:3,th:0,ti:4,tig:3,tk:3,tl:4,tn:3,to:0,tr:0,ts:3,tzm:22,uk:11,ur:3,ve:3,vi:0,vun:3,wa:4,wae:3,wo:0,xh:3,xog:3,yo:0,zh:0,zu:3}[c.replace(/-.*$/,"")];return f in d?d[f]:(console.warn("plural form unknown for ["+c+"]"),function(){return"other"})}function x(c,e,b){var d=g[c];if(!d){console.warn("#"+c+" is undefined.");if(!b)return null;
d=b}b={};for(var f in d){var a=d[f];var h=e,k=c,m=f,p=/\{\[\s*([a-zA-Z]+)\(([a-zA-Z]+)\)\s*\]\}/.exec(a);if(p&&p.length){var n=p[1],p=p[2],l=void 0;h&&p in h?l=h[p]:p in g&&(l=g[p]);n in q&&(a=(0,q[n])(a,l,k,m))}a=F(a,e,c);b[f]=a}return b}function F(c,e,b){return c.replace(/\{\{\s*(.+?)\s*\}\}/g,function(c,f){if(e&&f in e)return e[f];if(f in g)return g[f];console.log("argument {{"+f+"}} for #"+b+" is undefined.");return c})}function y(c){var e,b;if(c){e=c.getAttribute("data-l10n-id");var d=c.getAttribute("data-l10n-args");
b={};if(d)try{b=JSON.parse(d)}catch(f){console.warn("could not parse arguments for #"+e)}}else b=e=void 0;if(e)if(b=x(e,b)){if(b.textContent){if(c.children)e=c.children.length;else if("undefined"!==typeof c.childElementCount)e=c.childElementCount;else for(d=e=0;d<c.childNodes.length;d++)e+=1===c.nodeType?1:0;if(0===e)c.textContent=b.textContent;else{e=c.childNodes;for(var d=!1,a=0,g=e.length;a<g;a++)3===e[a].nodeType&&/\S/.test(e[a].nodeValue)&&(d?e[a].nodeValue="":(e[a].nodeValue=b.textContent,d=
!0));d||(e=k.createTextNode(b.textContent),c.insertBefore(e,c.firstChild))}delete b.textContent}for(var l in b)c[l]=b[l]}else console.warn("#"+e+" is undefined.")}function z(c){for(var e=(c=c||k.documentElement)?c.querySelectorAll("*[data-l10n-id]"):[],b=e.length,d=0;d<b;d++)y(e[d]);y(c)}var g={},l="",m="",q={},n="loading";q.plural=function(c,e,b,d){e=parseFloat(e);if(isNaN(e)||"textContent"!=d)return c;q._pluralRules||(q._pluralRules=E(m));var f="["+q._pluralRules(e)+"]";0===e&&b+"[zero]"in g?c=
g[b+"[zero]"][d]:1==e&&b+"[one]"in g?c=g[b+"[one]"][d]:2==e&&b+"[two]"in g?c=g[b+"[two]"][d]:b+f in g?c=g[b+f][d]:b+"[other]"in g&&(c=g[b+"[other]"][d]);return c};return{get:function(c,e,b){var d=c.lastIndexOf("."),f="textContent";0<d&&(f=c.substr(d+1),c=c.substring(0,d));var a;b&&(a={},a[f]=b);return(e=x(c,e,a))&&f in e?e[f]:"{{"+c+"}}"},getData:function(){return g},getText:function(){return l},getLanguage:function(){return m},setLanguage:function(c,e){D(c,function(){e&&e();z()})},getDirection:function(){var c=
m.split("-",1)[0];return 0<=["ar","he","fa","ps","ur"].indexOf(c)?"rtl":"ltr"},translate:z,getReadyState:function(){return n},ready:function(c){c&&("complete"==n||"interactive"==n?A.setTimeout(function(){c()}):k.addEventListener&&k.addEventListener("localized",function b(){k.removeEventListener("localized",b);c()}))}}}(window,document);
