var FontInspector=function(){function f(){for(var a=document.querySelectorAll("div[data-font-name]"),c=0,b=a.length;c<b;++c)a[c].className="debuggerHideText"}function h(a,c){for(var b=document.querySelectorAll("div[data-font-name="+a+"]"),k=0,d=b.length;k<d;++k)b[k].className=c?"debuggerShowText":"debuggerHideText"}function d(a){if(a.target.dataset.fontName&&"DIV"===a.target.tagName.toUpperCase()){a=a.target.dataset.fontName;for(var c=document.getElementsByTagName("input"),b=0;b<c.length;++b){var d=
c[b];d.dataset.fontName===a&&(d.checked=!d.checked,h(a,d.checked),d.scrollIntoView())}}}var e,b=!1;return{id:"FontInspector",name:"Font Inspector",panel:null,manager:null,init:function(){var a=this.panel;a.setAttribute("style","padding: 5px;");var c=document.createElement("button");c.addEventListener("click",f);c.textContent="Refresh";a.appendChild(c);e=document.createElement("div");a.appendChild(e)},cleanup:function(){e.textContent=""},enabled:!1,get active(){return b},set active(a){if(b=a)document.body.addEventListener("click",
d,!0),f();else{document.body.removeEventListener("click",d,!0);a=document.querySelectorAll("div[data-font-name]");for(var c=0,r=a.length;c<r;++c)a[c].className=""}},fontAdded:function(a,c){var b=function(a,c){for(var b=document.createElement("table"),d=0;d<c.length;d++){var r=document.createElement("tr"),e=document.createElement("td");e.textContent=c[d];r.appendChild(e);e=document.createElement("td");e.textContent=a[c[d]].toString();r.appendChild(e);b.appendChild(r)}return b}(a,["name","type"]),d=
a.loadedName,g=document.createElement("div"),n=document.createElement("span");n.textContent=d;var q=document.createElement("a");c?(c=/url\(['"]?([^\)"']+)/.exec(c),q.href=c[1]):a.data&&(c=URL.createObjectURL(new Blob([a.data],{type:a.mimeType})),q.href=c);q.textContent="Download";var p=document.createElement("a");p.href="";p.textContent="Log";p.addEventListener("click",function(c){c.preventDefault();console.log(a)});var l=document.createElement("input");l.setAttribute("type","checkbox");l.dataset.fontName=
d;l.addEventListener("click",function(a,c){return function(){h(c,a.checked)}}(l,d));g.appendChild(l);g.appendChild(n);g.appendChild(document.createTextNode(" "));g.appendChild(q);g.appendChild(document.createTextNode(" "));g.appendChild(p);g.appendChild(b);e.appendChild(g);setTimeout(function(){this.active&&f()}.bind(this),2E3)}}}(),StepperManager=function(){var f=[],h=null,d=null,e=null,b={};return{id:"Stepper",name:"Stepper",panel:null,manager:null,init:function(){var a=this;this.panel.setAttribute("style",
"padding: 5px;");d=document.createElement("div");e=document.createElement("select");e.addEventListener("change",function(c){a.selectStepper(this.value)});d.appendChild(e);h=document.createElement("div");this.panel.appendChild(d);this.panel.appendChild(h);sessionStorage.getItem("pdfjsBreakPoints")&&(b=JSON.parse(sessionStorage.getItem("pdfjsBreakPoints")))},cleanup:function(){e.textContent="";h.textContent="";f=[]},enabled:!1,active:!1,create:function(a){var c=document.createElement("div");c.id="stepper"+
a;c.setAttribute("hidden",!0);c.className="stepper";h.appendChild(c);var d=document.createElement("option");d.textContent="Page "+(a+1);d.value=a;e.appendChild(d);c=new Stepper(c,a,b[a]||[]);f.push(c);1===f.length&&this.selectStepper(a,!1);return c},selectStepper:function(a,c){var b;a|=0;c&&this.manager.selectPanel(this);for(b=0;b<f.length;++b){var d=f[b];d.pageIndex===a?d.panel.removeAttribute("hidden"):d.panel.setAttribute("hidden",!0)}d=e.options;for(b=0;b<d.length;++b){var g=d[b];g.selected=(g.value|
0)===a}},saveBreakPoints:function(a,c){b[a]=c;sessionStorage.setItem("pdfjsBreakPoints",JSON.stringify(b))}}}(),Stepper=function(){function f(b,a){var c=document.createElement(b);a&&(c.textContent=a);return c}function h(b){if("string"===typeof b)return 75>=b.length?b:b.substr(0,75)+"...";if("object"!==typeof b||null===b)return b;if("length"in b){var a=[],c,d;c=0;for(d=Math.min(10,b.length);c<d;c++)a.push(h(b[c]));c<b.length&&a.push("...");return a}a={};for(c in b)a[c]=h(b[c]);return a}function d(b,
a,c){this.panel=b;this.breakPoint=0;this.nextBreakPoint=null;this.pageIndex=a;this.breakPoints=c;this.currentIdx=-1;this.operatorListIdx=0}var e=null;d.prototype={init:function(){var b=this.panel,a=f("div","c=continue, s=step"),c=f("table");a.appendChild(c);c.cellSpacing=0;var d=f("tr");c.appendChild(d);d.appendChild(f("th","Break"));d.appendChild(f("th","Idx"));d.appendChild(f("th","fn"));d.appendChild(f("th","args"));b.appendChild(a);this.table=c;if(!e){e=Object.create(null);for(var k in PDFJS.OPS)e[PDFJS.OPS[k]]=
k}},updateOperatorList:function(b){function a(){var a=+this.dataset.idx;this.checked?c.breakPoints.push(a):c.breakPoints.splice(c.breakPoints.indexOf(a),1);StepperManager.saveBreakPoints(c.pageIndex,c.breakPoints)}var c=this;if(!(15E3<this.operatorListIdx)){for(var d=document.createDocumentFragment(),k=Math.min(15E3,b.fnArray.length),g=this.operatorListIdx;g<k;g++){var n=f("tr");n.className="line";n.dataset.idx=g;d.appendChild(n);var q=-1!==this.breakPoints.indexOf(g),p=b.argsArray[g]||[],l=f("td"),
m=f("input");m.type="checkbox";m.className="points";m.checked=q;m.dataset.idx=g;m.onclick=a;l.appendChild(m);n.appendChild(l);n.appendChild(f("td",g.toString()));q=e[b.fnArray[g]];l=p;if("showText"===q){for(var p=p[0],l=[],m=[],t=0;t<p.length;t++){var s=p[t];"object"===typeof s&&null!==s?m.push(s.fontChar):(0<m.length&&(l.push(m.join("")),m=[]),l.push(s))}0<m.length&&l.push(m.join(""));l=[l]}n.appendChild(f("td",q));n.appendChild(f("td",JSON.stringify(h(l))))}k<b.fnArray.length&&(n=f("tr"),k=f("td",
"..."),k.colspan=4,d.appendChild(k));this.operatorListIdx=b.fnArray.length;this.table.appendChild(d)}},getNextBreakPoint:function(){this.breakPoints.sort(function(a,c){return a-c});for(var b=0;b<this.breakPoints.length;b++)if(this.breakPoints[b]>this.currentIdx)return this.breakPoints[b];return null},breakIt:function(b,a){StepperManager.selectStepper(this.pageIndex,!0);var c=this,d=document;c.currentIdx=b;var e=function(b){switch(b.keyCode){case 83:d.removeEventListener("keydown",e,!1);c.nextBreakPoint=
c.currentIdx+1;c.goTo(-1);a();break;case 67:d.removeEventListener("keydown",e,!1),b=c.getNextBreakPoint(),c.nextBreakPoint=b,c.goTo(-1),a()}};d.addEventListener("keydown",e,!1);c.goTo(b)},goTo:function(b){for(var a=this.panel.getElementsByClassName("line"),c=0,d=a.length;c<d;++c){var e=a[c];(e.dataset.idx|0)===b?(e.style.backgroundColor="rgb(251,250,207)",e.scrollIntoView()):e.style.backgroundColor=null}}};return d}(),Stats=function(){function f(d){for(;d.hasChildNodes();)d.removeChild(d.lastChild)}
function h(e){for(var b=0,a=d.length;b<a;++b)if(d[b].pageNumber===e)return b;return!1}var d=[];return{id:"Stats",name:"Stats",panel:null,manager:null,init:function(){this.panel.setAttribute("style","padding: 5px;");PDFJS.enableStats=!0},enabled:!1,active:!1,add:function(e,b){if(b){var a=h(e);!1!==a&&(this.panel.removeChild(d[a].div),d.splice(a,1));a=document.createElement("div");a.className="stats";var c=document.createElement("div");c.className="title";c.textContent="Page: "+e;var r=document.createElement("div");
r.textContent=b.toString();a.appendChild(c);a.appendChild(r);d.push({pageNumber:e,div:a});d.sort(function(a,b){return a.pageNumber-b.pageNumber});f(this.panel);a=0;for(c=d.length;a<c;++a)this.panel.appendChild(d[a].div)}},cleanup:function(){d=[];f(this.panel)}}}(),PDFBug=function(){var f=[],h=null;return{tools:[FontInspector,StepperManager,Stats],enable:function(d){var e=!1,b=this.tools;1===d.length&&"all"===d[0]&&(e=!0);for(var a=0;a<b.length;++a){var c=b[a];if(e||-1!==d.indexOf(c.id))c.enabled=
!0}e||b.sort(function(a,c){var e=d.indexOf(a.id),e=0>e?b.length:e,f=d.indexOf(c.id),f=0>f?b.length:f;return e-f})},init:function(){var d=document.createElement("div");d.id="PDFBug";var e=document.createElement("div");e.setAttribute("class","controls");d.appendChild(e);var b=document.createElement("div");b.setAttribute("class","panels");d.appendChild(b);var a=document.getElementById("viewerContainer");a.appendChild(d);a.style.right="300px";for(var d=this.tools,c=this,a=0;a<d.length;++a){var h=d[a],
k=document.createElement("div"),g=document.createElement("button");g.textContent=h.name;g.addEventListener("click",function(a){return function(b){b.preventDefault();c.selectPanel(a)}}(a));e.appendChild(g);b.appendChild(k);h.panel=k;h.manager=this;h.enabled?h.init():k.textContent=h.name+' is disabled. To enable add  "'+h.id+'" to the pdfBug parameter and refresh (seperate multiple by commas).';f.push(g)}this.selectPanel(0)},cleanup:function(){for(var d=0,e=this.tools.length;d<e;d++)this.tools[d].enabled&&
this.tools[d].cleanup()},selectPanel:function(d){"number"!==typeof d&&(d=this.tools.indexOf(d));if(d!==h){h=d;for(var e=this.tools,b=0;b<e.length;++b)b===d?(f[b].setAttribute("class","active"),e[b].active=!0,e[b].panel.removeAttribute("hidden")):(f[b].setAttribute("class",""),e[b].active=!1,e[b].panel.setAttribute("hidden","true"))}}}}();
